version: 2.1
# Use a package of configuration called an orb.
defaults: &defaults
    docker:
    - image: circleci/node:13.8.0
commands:
    catfile:
        description: "list content of a file"
        parameters: 
            file: 
                type: string
                default: "workspace.txt"
        steps:
            - run: cat << parameters.file >>
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
